import { expect } from "bun:test";
import { requests } from "./helpers";
import { compatScenario } from "../../../support/scenario";
import { asArray, asRecord, signUpUser } from "../../phase6/helpers";


compatScenario("enabled teams preserve membership identity, active sessions and tenant boundaries", async (ctx) => {
  const owner = await signUpUser(ctx, "owner", "teams-owner", "Owner");
  const member = await signUpUser(ctx, "member", "teams-member", "Member");
  const outsider = await signUpUser(ctx, "outsider", "teams-outsider", "Outsider");
  const { call, observations } = requests(ctx);
  const org = asRecord(await call("owner", "create", { name: "Teams Organization", slug: ctx.uniqueToken("teams") }));
  const organizationId = org.id;
  const defaults = asArray(await call("owner", `list-teams?organizationId=${organizationId}`));
  expect(defaults).toHaveLength(1);
  const defaultTeam = asRecord(defaults[0]);
  expect(defaultTeam.organizationId).toBe(organizationId);
  expect(defaultTeam.name).toBe("Teams Organization");
  expect(defaultTeam.updatedAt).toBeNull();
  const ownerSession = await owner.client.getSession();
  expect(asRecord(ownerSession.data!.session).activeTeamId).toBe(defaultTeam.id);
  observations.push(ownerSession);
  const defaultMembers = asArray(await call("owner", `list-team-members?teamId=${defaultTeam.id}`));
  expect(asRecord(defaultMembers[0]).userId).toBe(owner.signup.data!.user.id);
  const full = asRecord(await call("owner", `get-full-organization?organizationId=${organizationId}`));
  expect(asArray(full.teams).map((value) => asRecord(value).id)).toEqual([defaultTeam.id]);
  const invitation = asRecord(await call("owner", "invite-member", { organizationId, email: member.email, role: "member" }));
  await call("member", "accept-invitation", { invitationId: invitation.id });
  const ignoredId = ctx.uniqueToken("unconfigured-team-id");
  const team = asRecord(await call("owner", "create-team", { organizationId, name: "Engineering", id: ignoredId }));
  expect(team.id).not.toBe(ignoredId);
  expect(team.organizationId).toBe(organizationId);
  const teamId = team.id;
  const memberId = member.signup.data!.user.id;
  await call("member", "create-team", { organizationId, name: "Forbidden" }, 403);
  await call("outsider", "list-teams?organizationId=" + organizationId, undefined, 403);
  await call("owner", "add-team-member", { organizationId, teamId, userId: outsider.signup.data!.user.id }, 400);
  const membership = asRecord(await call("owner", "add-team-member", { organizationId, teamId, userId: memberId }));
  expect(membership.teamId).toBe(teamId);
  expect(membership.userId).toBe(memberId);
  const duplicate = await call("owner", "add-team-member", { organizationId, teamId, userId: memberId });
  expect(duplicate).toEqual(membership);
  await call("member", "add-team-member", { organizationId, teamId, userId: owner.signup.data!.user.id }, 403);
  const listed = asArray(await call("member", `list-team-members?teamId=${teamId}`));
  expect(listed).toHaveLength(1);
  expect(asRecord(listed[0]).id).toBe(membership.id);
  const selfTeams = asArray(await call("member", "list-user-teams"));
  expect(selfTeams.map((value) => asRecord(value).id)).toContain(teamId);
  await call("owner", `list-user-teams?organizationId=${organizationId}&userId=${memberId}`);
  await call("outsider", "set-active-team", { teamId }, 400);
  const active = asRecord(await call("member", "set-active-team", { teamId }));
  expect(active.id).toBe(teamId);
  const session = await member.client.getSession();
  expect(asRecord(session.data!.session).activeTeamId).toBe(teamId);
  observations.push(session);
  const updated = asRecord(await call("owner", "update-team", { teamId, data: { organizationId, name: "Platform" } }));
  expect(updated.id).toBe(teamId);
  expect(updated.name).toBe("Platform");
  const other = asRecord(await call("owner", "create", { name: "Other Tenant", slug: ctx.uniqueToken("other") }));
  await call("owner", "update-team", { teamId, data: { organizationId: other.id, name: "Cross Tenant" } }, 400);
  await call("owner", "remove-team-member", { organizationId: other.id, teamId, userId: memberId }, 400);
  await call("owner", "remove-team-member", { organizationId, teamId, userId: memberId });
  await call("member", `list-team-members?teamId=${teamId}`, undefined, 400);
  await call("owner", "remove-team", { organizationId, teamId });
  const remaining = asArray(await call("owner", `list-teams?organizationId=${organizationId}`));
  expect(remaining.map((value) => asRecord(value).id)).toEqual([defaultTeam.id]);
  await call("owner", "remove-team", { organizationId, teamId: defaultTeam.id }, 400);
  expect(asArray(await call("member", "list-user-teams"))).toHaveLength(0);
  return observations;
});

compatScenario("dynamic roles persist permissions and enforce privilege and tenant boundaries", async (ctx) => {
  await signUpUser(ctx, "owner", "roles-owner", "Owner");
  const member = await signUpUser(ctx, "member", "roles-member", "Member");
  const admin = await signUpUser(ctx, "admin", "roles-admin", "Admin");
  await signUpUser(ctx, "outsider", "roles-outsider", "Outsider");
  const { call, observations } = requests(ctx);
  const org = asRecord(await call("owner", "create", { name: "Roles Organization", slug: ctx.uniqueToken("roles") }));
  const organizationId = org.id;
  let memberId: unknown;
  for (const [actor, email, role] of [["member", member.email, "member"], ["admin", admin.email, "admin"]]) {
    const invitation = asRecord(await call("owner", "invite-member", { organizationId, email, role }));
    const accepted = asRecord(await call(actor!, "accept-invitation", { invitationId: invitation.id }));
    if (actor === "member") memberId = asRecord(accepted.member).id;
  }
  const permission = { team: ["create"] };
  const created = asRecord(await call("owner", "create-role", { organizationId, role: "TeamCreator", permission }));
  expect(created.success).toBe(true);
  const role = asRecord(created.roleData);
  expect(role.role).toBe("teamcreator");
  expect(role.organizationId).toBe(organizationId);
  expect(role.permission).toEqual(permission);
  expect(created.statements).toEqual(permission);
  const roleId = role.id;
  expect(await call("member", `get-role?organizationId=${organizationId}&roleId=${roleId}`)).toEqual(role);
  expect(asArray(await call("member", `list-roles?organizationId=${organizationId}`))).toEqual([role]);
  await call("owner", "create-role", { organizationId, role: "TEAMCREATOR", permission }, 400);
  await call("owner", "create-role", { organizationId, role: "owner", permission }, 400);
  await call("member", "create-role", { organizationId, role: "forbidden", permission }, 403);
  await call("outsider", `list-roles?organizationId=${organizationId}`, undefined, 403);
  await call("admin", "create-role", { organizationId, role: "escalation", permission: { organization: ["delete"] } }, 403);
  await call("admin", "create-role", { organizationId, role: "ordered-denial", permission: { team: ["nonexistent"], organization: ["delete"] } }, 403);
  await call("owner", "create-role", { organizationId, role: "invalid", permission: { unknown: ["read"] } }, 400);
  await call("owner", "update-member-role", { organizationId, memberId, role: "teamcreator" });
  const allowed = asRecord(await call("member", "has-permission", { organizationId, permissions: permission }));
  expect(allowed.success).toBe(true);
  await call("member", "create-team", { organizationId, name: "Delegated Team" });
  const changed = asRecord(await call("owner", "update-role", { organizationId, roleId, data: { permission: { team: ["update"] } } }));
  expect(changed.success).toBe(true);
  await call("member", "create-team", { organizationId, name: "Revoked Permission" }, 403);
  const other = asRecord(await call("owner", "create", { name: "Other Roles Tenant", slug: ctx.uniqueToken("other-roles") }));
  await call("owner", `get-role?organizationId=${other.id}&roleId=${roleId}`, undefined, 400);
  await call("owner", "delete-role", { organizationId: other.id, roleId }, 400);
  await call("owner", "delete-role", { organizationId, roleId }, 400);
  await call("owner", "update-member-role", { organizationId, memberId, role: "member" });
  const renamed = asRecord(await call("owner", "update-role", { organizationId, roleId, data: { roleName: "RenamedRole" } }));
  expect(asRecord(renamed.roleData).role).toBe("renamedrole");
  const byName = asRecord(await call("owner", `get-role?organizationId=${organizationId}&roleName=renamedrole`));
  expect(byName.id).toBe(roleId);
  await call("owner", "delete-role", { organizationId, roleId });
  expect(asArray(await call("owner", `list-roles?organizationId=${organizationId}`))).toHaveLength(0);
  await call("member", "create-team", { organizationId, name: "Deleted Role" }, 403);
  return observations;
});

compatScenario("team invitations join the target team and clear deleted pending team references", async (ctx) => {
  await signUpUser(ctx, "owner", "invite-team-owner", "Owner");
  const member = await signUpUser(ctx, "member", "invite-team-member", "Member");
  const pending = await signUpUser(ctx, "pending", "invite-team-pending", "Pending");
  const { call, observations } = requests(ctx);
  const org = asRecord(await call("owner", "create", { name: "Invitation Teams", slug: ctx.uniqueToken("invite-teams") }));
  const organizationId = org.id;
  const team = asRecord(await call("owner", "create-team", { organizationId, name: "Invited Team" }));
  const teamId = team.id;
  const invitation = asRecord(await call("owner", "invite-member", { organizationId, teamId, email: member.email, role: "member" }));
  expect(invitation.teamId).toBe(teamId);
  await call("member", "accept-invitation", { invitationId: invitation.id });
  const joined = asArray(await call("member", `list-team-members?teamId=${teamId}`));
  expect(joined).toHaveLength(1);
  expect(asRecord(joined[0]).userId).toBe(member.signup.data!.user.id);
  const session = await member.client.getSession();
  expect(asRecord(session.data!.session).activeTeamId).toBe(teamId);
  observations.push(session);
  const waiting = asRecord(await call("owner", "invite-member", { organizationId, teamId, email: pending.email, role: "member" }));
  await call("owner", "remove-team", { organizationId, teamId });
  const invitations = asArray(await call("owner", `list-invitations?organizationId=${organizationId}`));
  expect(asRecord(invitations.find((value) => asRecord(value).id === waiting.id)).teamId).toBeNull();
  await call("pending", "accept-invitation", { invitationId: waiting.id });
  expect(asArray(await call("pending", "list-user-teams"))).toHaveLength(0);
  return observations;
});

compatScenario("dynamic role validation rejects null and missing selectors before mutation", async (ctx) => {
  await signUpUser(ctx, "owner", "validation-owner", "Owner");
  const { call, observations } = requests(ctx);
  await call("owner", "create-role", { role: "owner", permission: {} }, 400);
  const org = asRecord(await call("owner", "create", { name: "Validation Organization", slug: ctx.uniqueToken("validation") }));
  const organizationId = org.id;
  const created = asRecord(await call("owner", "create-role", { organizationId, role: "custom", permission: {} }));
  const roleId = asRecord(created.roleData).id;
  await call("owner", "update-role", { organizationId, roleId, data: { permission: null } }, 400);
  await call("owner", "update-role", { organizationId, roleId, data: { roleName: null } }, 400);
  await call("owner", "update-role", { organizationId, data: {} }, 400);
  await call("owner", "delete-role", { organizationId }, 400);
  await call("owner", "get-role", undefined, 400);
  await call("owner", `get-role?organizationId=${organizationId}`, undefined, 400);
  await call("owner", `get-role?organizationId=${organizationId}&roleName=`, undefined, 400);
  await call("owner", "update-role", { organizationId, roleName: "", data: {} }, 400);
  await call("owner", "delete-role", { organizationId, roleName: "" }, 400);
  expect(await call("owner", `get-role?organizationId=${organizationId}&roleId=${roleId}`)).toEqual(created.roleData);
  return observations;
});

compatScenario("multi-team invitations preserve every team identity without selecting an active team", async (ctx) => {
  await signUpUser(ctx, "owner", "multi-team-owner", "Owner");
  const member = await signUpUser(ctx, "member", "multi-team-member", "Member");
  const { call, observations } = requests(ctx);
  const org = asRecord(await call("owner", "create", { name: "Multi Team Organization", slug: ctx.uniqueToken("multi-team") }));
  const organizationId = org.id;
  const first = asRecord(await call("owner", "create-team", { organizationId, name: "First Team" }));
  const second = asRecord(await call("owner", "create-team", { organizationId, name: "Second Team" }));
  const teamIds = [first.id, second.id];
  const invitation = asRecord(await call("owner", "invite-member", { organizationId, teamId: teamIds, email: member.email, role: "member" }));
  expect(typeof invitation.teamId).toBe("string");
  expect((invitation.teamId as string).split(",")).toEqual(teamIds);
  const accepted = asRecord(await call("member", "accept-invitation", { invitationId: invitation.id }));
  expect(asRecord(accepted.invitation).teamId).toBe(invitation.teamId);
  expect(asRecord(accepted.member).userId).toBe(member.signup.data!.user.id);
  expect(asRecord(accepted.member).organizationId).toBe(organizationId);
  const membershipIds = [];
  for (const teamId of teamIds) {
    const memberships = asArray(await call("member", `list-team-members?teamId=${teamId}`));
    expect(memberships).toHaveLength(1);
    const membership = asRecord(memberships[0]);
    expect(membership.teamId).toBe(teamId);
    expect(membership.userId).toBe(member.signup.data!.user.id);
    membershipIds.push(membership.id);
  }
  expect(membershipIds[0]).not.toBe(membershipIds[1]);
  const teams = asArray(await call("member", "list-user-teams"));
  expect(teams.map((team) => asRecord(team).id)).toEqual(teamIds);
  const session = await member.client.getSession();
  expect(asRecord(session.data!.session).activeTeamId).toBeNull();
  expect(asRecord(session.data!.session).activeOrganizationId).toBe(organizationId);
  observations.push(session);
  return observations;
});
