import { expect } from "bun:test";
import { compatScenario } from "../../../support/scenario";
import { asArray, asRecord, signUpUser } from "../../phase6/helpers";
import { requests } from "../organization-extended/helpers";

compatScenario("team capacity, concurrent duplicate membership and dynamic-role limits persist", async (ctx) => {
  const owner = await signUpUser(ctx, "owner", "limits-owner", "Owner");
  const member = await signUpUser(ctx, "member", "limits-member", "Member");
  const { call, observations } = requests(ctx);
  const org = asRecord(await call("owner", "create", { name: "Limited Organization", slug: ctx.uniqueToken("limits") }));
  const organizationId = org.id;
  expect(asArray(await call("owner", `list-teams?organizationId=${organizationId}`))).toHaveLength(0);
  const invitation = asRecord(await call("owner", "invite-member", { organizationId, email: member.email, role: "member" }));
  await call("member", "accept-invitation", { invitationId: invitation.id });
  const team = asRecord(await call("owner", "create-team", { organizationId, name: "One" }));
  const second = asRecord(await call("owner", "create-team", { organizationId, name: "Two" }));
  await call("owner", "create-team", { organizationId, name: "Three" }, 400);
  const teamId = team.id;
  const results = await Promise.all([0, 1].map(() => call("owner", "add-team-member", { organizationId, teamId, userId: member.signup.data!.user.id })));
  expect(results[0]).toEqual(results[1]);
  const listed = asArray(await call("member", `list-team-members?teamId=${teamId}`));
  expect(listed).toHaveLength(1);
  expect(asRecord(listed[0]).id).toBe(asRecord(results[0]).id);
  await call("owner", "add-team-member", { organizationId, teamId, userId: owner.signup.data!.user.id }, 403);
  await call("owner", "remove-team-member", { organizationId, teamId, userId: member.signup.data!.user.id });
  await call("owner", "add-team-member", { organizationId, teamId, userId: owner.signup.data!.user.id });
  await call("owner", "remove-team", { organizationId, teamId });
  await call("owner", "remove-team", { organizationId, teamId: second.id });
  expect(asArray(await call("owner", `list-teams?organizationId=${organizationId}`))).toHaveLength(0);
  expect(asArray(await call("owner", "list-user-teams"))).toHaveLength(0);
  const role = asRecord(await call("owner", "create-role", { organizationId, role: "first", permission: { team: ["create"] } }));
  await call("owner", "create-role", { organizationId, role: "second", permission: {} }, 400);
  await call("owner", "delete-role", { organizationId, roleId: asRecord(role.roleData).id });
  await call("owner", "create-role", { organizationId, role: "replacement", permission: {} });
  return observations;
});

compatScenario("failed team invitation acceptance rolls back membership and remains retryable", async (ctx) => {
  const owner = await signUpUser(ctx, "owner", "rollback-owner", "Owner");
  const member = await signUpUser(ctx, "member", "rollback-member", "Member");
  const { call, observations } = requests(ctx);
  const org = asRecord(await call("owner", "create", { name: "Rollback Organization", slug: ctx.uniqueToken("rollback") }));
  const organizationId = org.id;
  const team = asRecord(await call("owner", "create-team", { organizationId, name: "Capacity" }));
  const teamId = team.id;
  const invitation = asRecord(await call("owner", "invite-member", { organizationId, teamId, email: member.email, role: "member" }));
  await call("owner", "add-team-member", { organizationId, teamId, userId: owner.signup.data!.user.id });
  await call("member", "accept-invitation", { invitationId: invitation.id }, 403);
  const invitations = asArray(await call("owner", `list-invitations?organizationId=${organizationId}`));
  expect(asRecord(invitations.find((value) => asRecord(value).id === invitation.id)).status).toBe("pending");
  const members = asRecord(await call("owner", `list-members?organizationId=${organizationId}`));
  expect(asArray(members.members)).toHaveLength(1);
  expect(asArray(await call("member", "list-user-teams"))).toHaveLength(0);
  await call("owner", "remove-team-member", { organizationId, teamId, userId: owner.signup.data!.user.id });
  await call("member", "accept-invitation", { invitationId: invitation.id });
  const joined = asArray(await call("member", `list-team-members?teamId=${teamId}`));
  expect(asRecord(joined[0]).userId).toBe(member.signup.data!.user.id);
  return observations;
});
