[package]
name = "compat-rust-server"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
better-auth = { path = "../..", features = ["axum", "seaorm2"], version = "1.0.0-alpha.3" }
better-auth-core = { path = "../../crates/core" }
better-auth-seaorm = { path = "../../crates/seaorm" }
tokio = { version = "1", features = ["full"] }
axum = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower-http = { version = "0.6", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1.89"
chrono = "0.4.44"
url = "2.5.8"
k256 = { version = "0.14.0", features = ["ecdsa"] }
sha3 = "0.12.0"
